# Generated by Django 6.0.4 on 2026-04-18 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('topology', '0003_alter_feeder_curr_load_mw'),
    ]

    operations = [
        migrations.CreateModel(
            name='Efficiency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('tot_mw_suppl', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tot_rev_expec', models.DecimalField(decimal_places=2, max_digits=15)),
                ('tot_rev_collec', models.DecimalField(decimal_places=2, max_digits=15)),
                ('effic_ratio', models.DecimalField(decimal_places=2, max_digits=5)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perf_records', to='topology.grid')),
            ],
        ),
        migrations.CreateModel(
            name='LoadPredict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predi_date', models.DateField()),
                ('predi_peak_dem_mw', models.DecimalField(decimal_places=2, max_digits=12)),
                ('predi_shortfall_mw', models.DecimalField(decimal_places=2, max_digits=12)),
                ('confi_score', models.IntegerField(default=80)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='load_predicts', to='topology.grid')),
            ],
        ),
        migrations.CreateModel(
            name='Sustainability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('curr_deficit', models.DecimalField(decimal_places=2, max_digits=16)),
                ('improv_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('is_sustainable', models.BooleanField(default=False)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sustain_stats', to='topology.grid')),
            ],
        ),
    ]
