# Generated by Django 6.0.4 on 2026-04-13 12:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('topology', '0003_alter_feeder_curr_load_mw'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingAcc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('culprit', models.BooleanField(default=False)),
                ('branch', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='billing_data', to='topology.branch')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_accounts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FeedFinanHealth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reco_percent', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('tot_defecit', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('feeder', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='finan_health', to='topology.feeder')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentRec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date_paid', models.DateTimeField(auto_now_add=True)),
                ('reference_id', models.CharField(max_length=60, unique=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='economics.billingacc')),
            ],
        ),
    ]
