# Generated by Django 6.0.4 on 2026-04-15 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('topology', '0003_alter_feeder_curr_load_mw'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriorityWeight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factor_name', models.CharField(max_length=70, unique=True)),
                ('weight_value', models.DecimalField(decimal_places=2, max_digits=6)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='FeedPriorScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('final_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('rank_in_zone', models.PositiveIntegerField(blank=True, null=True)),
                ('calculated_at', models.DateTimeField(auto_now=True)),
                ('feeder', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='priority_data', to='topology.feeder')),
            ],
            options={
                'ordering': ['-final_score'],
            },
        ),
    ]
