# Generated by Django 6.0.4 on 2026-04-18 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('responders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=70),
        ),
    ]
