# Generated by Django 6.0.4 on 2026-04-18 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auditrecord_delete_systemauditlog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuditRecord',
        ),
    ]
