# Generated by Django 6.0.4 on 2026-04-11 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Substation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('max_capacity_mw', models.DecimalField(decimal_places=2, max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substations', to='topology.grid')),
            ],
        ),
        migrations.CreateModel(
            name='Feeder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('current_load_mw', models.DecimalField(decimal_places=2, max_digits=12)),
                ('is_shedding_active', models.BooleanField(default=False)),
                ('is_energized', models.BooleanField(default=True)),
                ('substation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feeders', to='topology.substation')),
            ],
        ),
        migrations.CreateModel(
            name='Transformer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=70, unique=True)),
                ('kva_rating', models.IntegerField()),
                ('is_energized', models.BooleanField(default=True)),
                ('feeder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transformers', to='topology.feeder')),
            ],
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=60, unique=True)),
                ('node_type', models.CharField(choices=[('residential', 'Residential'), ('industrial', 'Industrial'), ('important', 'Important')], default='residential', max_length=60)),
                ('is_energized', models.BooleanField(default=True)),
                ('transformer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='topology.transformer')),
            ],
        ),
    ]
