# Generated by Django 6.0.4 on 2026-04-11 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topology', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='branch',
            old_name='node_type',
            new_name='type',
        ),
        migrations.RenameField(
            model_name='feeder',
            old_name='current_load_mw',
            new_name='curr_load_mw',
        ),
        migrations.RenameField(
            model_name='substation',
            old_name='max_capacity_mw',
            new_name='max_capa_mw',
        ),
    ]
