# Generated by Django 6.0.4 on 2026-04-12 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topology', '0002_rename_node_type_branch_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feeder',
            name='curr_load_mw',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
