# Generated by Django 6.0.4 on 2026-04-17 03:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('metering', '0001_initial'),
        ('responders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=70)),
                ('object_id', models.PositiveIntegerField()),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=45)),
                ('status', models.CharField(choices=[('assigned', 'Assigned'), ('ongoing', 'Ongoing'), ('solved', 'Solved'), ('failed', 'Failed')], default='assigned', max_length=45)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('assigned', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='responders.team')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='Investigation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evid_image', models.ImageField(blank=True, null=True, upload_to='theft_evidence/')),
                ('finding_notes', models.TextField(blank=True)),
                ('abnorma', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='investigation', to='metering.lossabnormality')),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='investigation_details', to='tasks.maintenance')),
            ],
        ),
    ]
