# Generated by Django 6.0.4 on 2026-04-16 13:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scheduler', '0001_initial'),
        ('topology', '0003_alter_feeder_curr_load_mw'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CancelRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('dura_mins', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('emergency', models.BooleanField(default=False)),
                ('feeder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manual_cancel', to='topology.feeder')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancel', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GridWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_kind', models.CharField(choices=[('shed', 'Shed'), ('restore', 'Restore')], default='shed', max_length=50)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('confirmed', 'Confirmed'), ('failed', 'Failed')], default='sent', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('feeder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commands', to='topology.feeder')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exec_work', to='scheduler.loadbalplan')),
            ],
        ),
        migrations.CreateModel(
            name='HardwareFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_payload', models.JSONField()),
                ('delay_ms', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('load_at_feedback', models.DecimalField(decimal_places=2, max_digits=12)),
                ('work', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_data', to='execution.gridwork')),
            ],
        ),
    ]
