# Generated by Django 6.0.4 on 2026-04-12 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('topology', '0003_alter_feeder_curr_load_mw'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuelType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=60, unique=True)),
                ('renewable', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GenerationUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('unit_name', models.CharField(max_length=70)),
                ('installed_capacity_mw', models.DecimalField(decimal_places=2, max_digits=12)),
                ('curr_output_mw', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('cost_per_unit', models.DecimalField(decimal_places=2, max_digits=12)),
                ('operational', models.BooleanField(default=True)),
                ('fuel_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='units', to='resources.fueltype')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GenerationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('output_mw', models.DecimalField(decimal_places=2, max_digits=12)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='resources.generationunit')),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='PowerSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=70, unique=True)),
                ('location', models.CharField(max_length=70)),
                ('owner_type', models.CharField(choices=[('state', 'State'), ('private', 'Private')], default='state', max_length=60)),
                ('grid_zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='power_sources', to='topology.grid')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='generationunit',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='resources.powersource'),
        ),
    ]
