# Generated by Django 6.0.4 on 2026-04-16 06:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('topology', '0003_alter_feeder_curr_load_mw'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('executing', 'Executing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=50)),
                ('total_mw_saved', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_cycles', to=settings.AUTH_USER_MODEL)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cycles', to='topology.grid')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LoadBalPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prior_at_exec', models.DecimalField(decimal_places=2, max_digits=12)),
                ('rank_at_exec', models.PositiveIntegerField()),
                ('planned_off_time', models.DateTimeField()),
                ('planned_on_time', models.DateTimeField()),
                ('is_executed', models.BooleanField(default=False)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='scheduler.cycle')),
                ('feeder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shedding_plans', to='topology.feeder')),
            ],
        ),
        migrations.CreateModel(
            name='SheddingTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('needed_red_mw', models.DecimalField(decimal_places=2, max_digits=12)),
                ('start_time', models.DateTimeField()),
                ('expec_dura_mins', models.PositiveIntegerField()),
                ('is_addressed', models.BooleanField(default=False)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_targets', to='topology.grid')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='cycle',
            name='target',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cycle', to='scheduler.sheddingtarget'),
        ),
    ]
